spring.application.name=AdopcionesApp
server.port=8000
#Conexion a Mysql
spring.datasource.url=jdbc:mysql://localhost:3306/dbAdopciones_in5am?createDatabaseIfNotExist=true
spring.datasource.username=Soloman
spring.datasource.password=Soloman90


#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
